name: backend
on:
  push:
    paths: ["backend/**"]
  workflow_dispatch:

env:
  RG: rg-ect2-dev-reem
  BACKEND_APP: web-backend-ect2-reem
  JAVA_VERSION: "17"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Enable public access (temporarily)
        run: |
          az webapp update -g "$RG" -n "$BACKEND_APP" --set publicNetworkAccess=Enabled

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - name: Build (skip tests)
        run: mvn -B -DskipTests package

      - name: Deploy jar to App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.BACKEND_APP }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND }}
          package: backend/target/*.jar

      - name: Disable public access (always)
        if: always()
        run: |
          az webapp update -g "$RG" -n "$BACKEND_APP" --set publicNetworkAccess=Disabled

