name: frontend
on:
  push:
    paths: ["frontend/**"]
  workflow_dispatch:

env:
  RG: rg-ect2-dev-reem
  FRONTEND_APP: web-frontend-ect2-reem
  NODE_VERSION: "18"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Enable public access (temporarily)
        run: |
          az webapp update -g "$RG" -n "$FRONTEND_APP" --set publicNetworkAccess=Enabled

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Zip build
        run: |
          cd dist
          zip -r ../frontend.zip .

      - name: Deploy static build to App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.FRONTEND_APP }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FRONTEND }}
          package: frontend/frontend.zip

      - name: Disable public access (always)
        if: always()
        run: |
          az webapp update -g "$RG" -n "$FRONTEND_APP" --set publicNetworkAccess=Disabled

